name: Generate Snake

on:
  schedule:
    # A cada 6 horas
    - cron: "0 */6 * * *"

# Permite executar a Action automaticamente na aba Actions.
workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Generate the snake
        id: snake-gif
        uses: Platane/snk@master
        with:
          github_user_name: vmatheuscouto
        env:
          GIF_PATH: dist/github-contribution-grid-snake.gif
          SVG_PATH: dist/github-contribution-grid-snake.svg

      - run: git status

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
